defaults: &defaults
  ftp_timeout: 3600
  smb_timeout: 3600
  http_timeout: 3600
  folder_timeout: 3600
  max_emails: 10000

  emex_login: 56281
  emex_password: IYQe4Bac
  # Время кеширования результата запроса с емекса по детали
  emex_cache: 100000000
  emex_timeout: 10000000

  lc_ws_address: http://192.168.1.42/trade_dda/ws
  lc_ws_login: webservice_test
  lc_ws_password: webservice_test

  catalog_number_len: 20
  manufacturer_len: 20
  max_replaces: 120
  
  prices_discount: 0.87

development:
  <<: *defaults

production:
  <<: *defaults
